[build-system]
requires = [
    "setuptools>=57",
    "wheel",
    "Keras==2.4.3",
    "silence-tensorflow==1.1.1",
    "tensorflow==2.2.0",
    "scikit-learn==0.22.2.post1",
    "scipy==1.4.1",
    "h5py==2.10.0",
    "scipy==1.4.1"
]
build-backend = "setuptools.build_meta"
